name: Deploy Site

on:
  push:
    branches:
      - main
    paths:
      - "./02 Starting Project/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./02 Starting Project" # ✅ Set once for all steps
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pwd
          npm install
      - name: Lint code
        run: npm run lint
      - name: Run tests
        run: npm run test
  
  build:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./02 Starting Project" # ✅ Set once for all steps
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pwd
          npm install
      - name: Build
        run: |
          npm run build
          ls -la
    #   - name: Upload artifact
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: artifact-name
    #       path: ./build

  deploy:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./02 Starting Project" # ✅ Set once for all steps
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy
        run: echo "Deploying..."
