name: Deploy Site

on:
  push:
    branches:
      - test

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./02 Starting Project" # ✅ Set once for all steps
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pwd
          npm install
      - name: Run tests
        run: npm run test
  
  build:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./02 Starting Project" # ✅ Set once for all steps
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pwd
          npm install
      - name: Build
        run: |
          npm run build
      - run: ls -la
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-name
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./02 Starting Project" # ✅ Set once for all steps
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy
        run: echo "Deploying..."
